### ISSUE TITLE
Mod Analytics 

### ISSUE THREAD

**Issue by jrddunbr** [eln2/eln2#172]
- [ ] Opt-Out Config
- [ ] Initial Analytics packet
- [ ] Block place/remove counter
- [ ] Final Analytics packet

Initial packet:
* UUID (not the Minecraft one, just a unique one generated and placed in `.minecraft/age-series-uuid.txt`.
* Operating System Language
* Game Language

Final Packet:
* UUID (not the Minecraft one, just a unique one generated and placed in `.minecraft/age-series-uuid.txt`.
* Blocks placed/removed (to gather utilization data to track if they are in a large modpack or actually being played)
* Average tick speed

We need to add an analytics endpoint so that we can see how the mod is performing and get user preferences (for example, languages we should support).

I want to do a thing where we send an initial analytics packet when they start the mod and another every time they leave a world, and add a counter that counts block placement and removals so that we can see if the mod is just loaded or if they actually play with it. My reasoning is that mods are often collected into major packs but that doesn’t really indicate whether they actually played it or enjoyed it.

Also, for languages, I want to get the system language and the game language because some people don’t use the game language settings because it’s poorly supported in some mods.

**Comment by jrddunbr** [comment]
Analytics endpoint is up, just working on the domain name work to actually dump it where it needs to go from the game and write the game code.
